[metadata]
name = localstack-extension-pgvector
version = 0.1.0
description = LocalStack extension to enable pgvector automatically
author = Muhammad Ikhwan Fathulloh
author_email = muhammadikhwanfathulloh17@gmail.com

[options]
packages = find:
install_requires =
    localstack-ext>=1.0.0

[options.entry_points]
localstack.extensions =
    pgvector = extension:PgVectorExtension
